Created ShoppingCart and CartItem model. Added ShoppingCart controller
GlebPashko/book-store pull request #11
Opened 2024-10-08 14:31 UTC by GlebPashko

2024-10-08 14:54 UTC, Elena-Bruyako requested changes
see comments

2024-10-08 14:54 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        shoppingCart.setCartItems(cartItemRepository.findByShoppingCartId(shoppingCart.getId()));
```suggestion
```

2024-10-08 14:54 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(id)
```suggestion
        ShoppingCart cart = repository.findByUserId(userId);
        CartItem cartItem = itemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId())
```

update quantity

2024-10-08 14:54 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/12-create-shopping_cart_cart-items-table.yml
> +                    foreignKeyName: fk_shoppingcartcartitems_shopping_carts
bad naming for fk (not readable)

2024-10-11 12:25 UTC, Elena-Bruyako requested changes
see comments

2024-10-11 12:25 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-10-11 12:25 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/ShoppingCartServiceImpl.java
> +                .orElseThrow(() -> new NoSuchElementException("Book not found"));
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("Book not found"));
```

provide book id to message

2024-10-11 12:25 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        return shoppingCartMapper.toShoppingCartResponseDto(shoppingCart);
check in postman that you get shop cart with cartItems (and in DB also)

2024-10-11 15:48 UTC, ahoienko approved these changes
Good job!

2024-10-14 17:49 UTC, merged