Added docker
GlebPashko/book-store pull request #13
Opened 2024-10-28 16:43 UTC by GlebPashko

2024-10-28 20:43 UTC, sarakhmen requested changes
please add minor improvement ;)

2024-10-29 08:02 UTC, liliia-ponomarenko approved these changes
Good job! A few comments. Also better add env.sample file ;)

2024-10-29 08:02 UTC, liliia-ponomarenko commented on src/main/resources/application.properties
>  spring.jpa.open-in-view=false
Better return it if you want to have the possibility to run your project locally

2024-10-29 08:02 UTC, liliia-ponomarenko commented on Dockerfile
> +EXPOSE 8080
add one empty line to the end of the file ;)

2024-10-29 08:02 UTC, liliia-ponomarenko commented on docker-compose.yml
> +      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:$DEBUG_PORT"
the same

2024-10-29 12:25 UTC, merged