Spring Boot web
GlebPashko/book-store pull request #2
Opened 2024-08-18 11:37 UTC by GlebPashko

2024-08-20 06:40 UTC, Elena-Bruyako requested changes
see comments

2024-08-20 06:40 UTC, Elena-Bruyako commented on pom.xml
> +            <version>1.5.5.Final</version>
create property for version

2024-08-20 06:40 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/controller/BookController.java
> +    public List getAll() {
```suggestion
    public List<BookDto> getAll() {
```

2024-08-20 06:40 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(savedBook);
```suggestion
        bookRepository.save(book);
        return bookMapper.toDto(book);
```

2024-08-20 06:40 UTC, Elena-Bruyako commented on src/main/java/org/example/bookstore/service/impl/BookServiceImpl.java
> +                        "Employee with id: " + id + " not found"));
wrong message

2024-08-21 11:14 UTC, okuzan commented on src/main/java/org/example/bookstore/dto/BookDto.java
> +@Setter
We need to use Getter and Setter instead of data for JPA Entity, but it's ok to just use Data for DTOs

2024-08-22 13:41 UTC, merged